#!/bin/bash
BASE=/home/ff/cs186/sp12/hw2/part1/data
psql -e -d postgres < $BASE/../schema.sql
psql -e -d USASpending -c "COPY lookup_agency_code FROM '$BASE/lookup_agency_code.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_assistance_type FROM '$BASE/lookup_assistance_type.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_attributes_config FROM '$BASE/lookup_attributes_config.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_cfda_current FROM '$BASE/lookup_cfda_current.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_compete_cat FROM '$BASE/lookup_compete_cat.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_cong_districts FROM '$BASE/lookup_cong_districts.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_country_code FROM '$BASE/lookup_country_code.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_district_cd FROM '$BASE/lookup_district_cd.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_extent_competed FROM '$BASE/lookup_extent_competed.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_major_agency FROM '$BASE/lookup_major_agency.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_majpsc_code FROM '$BASE/lookup_majpsc_code.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_naics_cd FROM '$BASE/lookup_naics_cd.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_obseleteagencies FROM '$BASE/lookup_obseleteagencies.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_omb_treasury_codes FROM '$BASE/lookup_omb_treasury_codes.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_pricing_code FROM '$BASE/lookup_pricing_code.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_program_source FROM '$BASE/lookup_program_source.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_psc_code FROM '$BASE/lookup_psc_code.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_reason_code FROM '$BASE/lookup_reason_code.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_reason_mod_code FROM '$BASE/lookup_reason_mod_code.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_recipient_type FROM '$BASE/lookup_recipient_type.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_regularized_statenames FROM '$BASE/lookup_regularized_statenames.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_setaside_code FROM '$BASE/lookup_setaside_code.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_spending_type FROM '$BASE/lookup_spending_type.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_state FROM '$BASE/lookup_state.csv' WITH CSV"
psql -e -d USASpending -c "COPY lookup_treasury_account FROM '$BASE/lookup_treasury_account.csv' WITH CSV"
psql -e -d USASpending -c "COPY state_population FROM '$BASE/state_population.csv' WITH CSV"
psql -e -d USASpending -c "COPY cong_dist_population FROM '$BASE/cong_dist_population.csv' WITH CSV"
psql -e -d USASpending -c "COPY dsvt_agency_cd FROM '$BASE/dsvt_agency_cd.csv' WITH CSV"
psql -e -d USASpending -c "COPY faads_main FROM '$BASE/faads_main_la.csv' WITH CSV"
psql -e -d USASpending -c "COPY faads_main FROM '$BASE/faads_clemson.csv' WITH CSV"
psql -e -d USASpending -c "COPY fpds_award_details FROM '$BASE/fpds_award_details_la.csv' WITH CSV"
psql -e -d USASpending -c "COPY fpds_award_details FROM '$BASE/fpds_award_regents.csv' WITH CSV"
psql -e -d USASpending -c "COPY fpds_contract_vendors FROM '$BASE/fpds_contract_vendors_la.csv' WITH CSV"
psql -e -d USASpending -c "ANALYZE"
